[tools]
age = "latest"
helm = "latest"
sops = "latest"
flux2 = "latest"
gh = "latest"
k9s = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
python = "latest"
terraform = "latest"

[env]
KUBECONFIG = "/workspaces/$DEVPOD_WORKSPACE_ID/kubeconfig"
