apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "b2dc1159-d3dd-47ca-a985-b9b4e4abc487"
      - op: replace
        path: /spec/parameters/tenantId
        value: "a248dd94-48b7-4395-a74f-2d3e5962bb6b"
