apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "d721a52e-6e33-4e37-b725-36eb78755430"
      - op: replace
        path: /spec/parameters/tenantId
        value: "a248dd94-48b7-4395-a74f-2d3e5962bb6b"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://n8npeejaybackupsstaging.blob.core.windows.net/customer1"
  - target:
      kind: Ingress
      name: customer1-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "customer1.mercury-staging.peejay-tech.com"
      - op: replace
        path: /spec/rules/0/host
        value: "customer1.mercury-staging.peejay-tech.com"
